;----
		LIST		P=12F675
		INCLUDE		P12F675.INC

;---
		CB			=	_CPD_OFF
		CB			&=	_CP_OFF
		CB			&=	_BODEN_ON
		CB			&=	_MCLRE_OFF
		CB			&=	_PWRTE_ON
		CB			&=	_WDT_OFF
		CB			&=	_INTRC_OSC_NOCLKOUT
		__CONFIG	CB

;---
		CBLOCK		H'20'
		CNT1
		CNT2
		CNT3
		CNT4
		BASE_TMR0			;BaseTimer 20000uS D'174'=21005, D'177'=20237
		HIGH_PULSE			;
		HIGH_PULSE_TEMP		;
		HIGH_PULSE_TEMP2		;
		H04_WTEMP			;
		ENDC

;---
		ORG			0
		GOTO		INIT
		ORG			4
		GOTO		H04
;---
H04
		MOVWF		H04_WTEMP
		BCF			INTCON,GIE
		BTFSC		INTCON,T0IF
		GOTO		H04_T0IE
		BTFSC		INTCON,INTF
		GOTO		H04_INTE
		GOTO		H04_RETFIE
		
H04_INTE
		INCF		HIGH_PULSE,f
		BCF			INTCON,INTF
		GOTO		H04_RETFIE
H04_T0IE
		MOVF		BASE_TMR0,w
		MOVWF		TMR0
		BSF			GPIO,4
		BSF			GPIO,5
		BCF			INTCON,T0IF
		MOVF		HIGH_PULSE,w
		MOVWF		HIGH_PULSE_TEMP
		NOP
		NOP
		NOP
		NOP
		NOP
		NOP
		DECFSZ		HIGH_PULSE_TEMP,f
		GOTO		$-7
		BCF			GPIO,4
		BCF			GPIO,5
		GOTO		H04_RETFIE

H04_RETFIE

		MOVF		H04_WTEMP,w
		BCF			INTCON,T0IF
		BCF			INTCON,INTF
		BSF			INTCON,GIE
		RETFIE

;---
INIT
		BSF			STATUS,RP0
		CALL		H'3FF'
		MOVWF		OSCCAL
		CLRF		ANSEL
		MOVLW		B'00001111'
		MOVWF		TRISIO

		BCF			OPTION_REG,T0CS
		BCF			OPTION_REG,PSA
		BSF			OPTION_REG,PS2
		BSF			OPTION_REG,PS1
		BSF			OPTION_REG,PS0

		BCF			STATUS,RP0
		MOVLW		B'00000111'
		MOVWF		CMCON
		CALL		TIMER2
		
		MOVLW		D'174'			;174
		MOVWF		BASE_TMR0;
		MOVWF		TMR0;
		BSF			INTCON,INTE
		BSF			INTCON,T0IE
		BCF			INTCON,T0IF	
		BSF			INTCON,GIE
		CLRF		GPIO;


;---
;		MOVL		D'55'		498uS
;		MOVL		D'100'		903uS
;		MOVL		D'167'		1506uS  167
;		MOVL		D'233'		2100uS  
;		233-100 = 133
;		133/120 = 1.1
MAIN
		MOVLW		D'244'
		MOVWF		HIGH_PULSE
		CALL		TIMER3
		MOVLW		D'50'
		MOVWF		HIGH_PULSE
		CALL		TIMER3
		MOVLW		D'147'
		MOVWF		HIGH_PULSE
		CALL		TIMER3

		NOP
		BTFSC		GPIO,0
		NOP
		BTFSS		GPIO,0 
		INCF		HIGH_PULSE,f
		CALL		TIMER2
		GOTO		$-3
		GOTO		PEND

;---
TIMER1
		MOVLW		D'25'
		MOVWF		CNT1
		NOP
		DECFSZ		CNT1,f
		GOTO		$-2
		RETURN

TIMER2
		MOVLW		D'100'
		MOVWF		CNT2
		NOP
		CALL		TIMER1
		DECFSZ		CNT2,f
		GOTO		$-3
		RETURN

TIMER3
		MOVLW		D'50'		;0.5s
		MOVWF		CNT3
		NOP
		CALL		TIMER2
		DECFSZ		CNT3,f
		GOTO		$-3
		RETURN

TIMER4
		MOVLW		D'10'		;10s
		MOVWF		CNT4
		NOP
		CALL		TIMER3
		DECFSZ		CNT4,f
		GOTO		$-3
		RETURN	

;---
PEND
		END